# Generated by Django 3.2.13 on 2023-09-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('releaseDate', models.DateField()),
                ('director', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
