# Generated by Django 3.2.13 on 2023-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecatalog', '0003_quizmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmovie',
            name='subgenre',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
