# Generated by Django 3.2.13 on 2023-11-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecatalog', '0005_quizresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresults',
            name='permaFavGenre',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
