# Generated by Django 3.2.13 on 2023-11-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecatalog', '0007_alter_quizresults_permafavgenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='pos',
            field=models.IntegerField(null=True),
        ),
    ]
