# Generated by Django 3.2.13 on 2023-11-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecatalog', '0008_quizresults_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('generofav', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
