# Generated by Django 3.2.13 on 2023-11-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecatalog', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='quizmovie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='images/posters'),
        ),
    ]
