# Generated by Django 3.2.13 on 2023-12-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecatalog', '0014_auto_20231209_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='generofav',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
