# Generated by Django 3.2.13 on 2023-12-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecatalog', '0015_alter_userprofile_generofav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='Olá, estou usando o MovieMatch!', null=True),
        ),
    ]
